name: web
on: [push, pull_request]

jobs:
  web-build:
    runs-on: ubuntu-latest
    container: emscripten/emsdk:latest
    env:
      buildDir: '${{ github.workspace }}/build'
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
    
      - name: Install vcpkg
        run: |
          whereis em++
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh
          echo "$GITHUB_WORKSPACE/vcpkg" >> $GITHUB_PATH
      
      - name: Build with CMakeSettings.json targeting WASM
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeSettingsJson
          configurationRegexFilter: 'Emscripten Linux Release'
          cmakeAppendedArgs: '-DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=wasm32-emscripten -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake'
          cmakeWrapperCommand: emcmake
          buildDirectory: ${{ env.buildDir }}
          
      - name: Print Build Directory Path
        run: | 
          
          cd build
          cd Emscripten\ Linux\ Release
          mkdir web-release
          mv Graphics.js web-release/
          mv Graphics.wasm web-release/
          mv Graphics.data web-release/
          cd ..
          cd ..
          mv index.html build/
          cd build
          mv index.html Emscripten\ Linux\ Release
          cd Emscripten\ Linux\ Release
          mv index.html web-release/
          

      - name: Configure safe directory for Git
        run: git config --global --add safe.directory /__w/EmscriptenOpengl/EmscriptenOpengl
          
      - name: Upload Benchmark Results as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: web-release/
          path: web-release/

      - name: Move Dir to tmp
        run: |
          echo "Current dir"
          cd build
          cd Emscripten\ Linux\ Release
          dir
          mv web-release/ /tmp/
          dir /tmp/

      - name: Checkout default branch
        uses: actions/checkout@v2

      - name: Create or Checkout gh-pages branch
        run: |
          git fetch
          git checkout gh-pages || (git checkout --orphan gh-pages && git rm -rf .)
      
      - name: Move Results Back from Temp Directory
        run: | 
          mv /tmp/web-release/index.html ./
          mv /tmp/web-release/Graphics.js ./
          mv /tmp/web-release/Graphics.wasm ./
          mv /tmp/web-release/Graphics.data ./

      - name: Commit and Push to gh-pages
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.html
          git add Graphics.js
          git add Graphics.wasm
          git commit -m "Add release" || echo "No changes to commit"
          git push https://${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}} gh-pages
      
  

